# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# echo Add other tasks to build, test, and deploy your project.
# echo See https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: npm install
  displayName: 'Run a multi-line script'

- script: npm run build
  displayName: 'Run a build'

- task: CopyFiles@2
  inputs:
    Contents: '**' ## update to match what you want to copy
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files

    
# - task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(System.DefaultWorkingDirectory)'