# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# echo Add other tasks to build, test, and deploy your project.
# echo See https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: npm install
  displayName: 'Run a multi-line script'

- script: npm run build
  displayName: 'Run a build'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **\*.js
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.app).zip'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    pathToPublish: '$(build.artifactstagingdirectory)/$(Build.app).zip'
    artifactName: app
    artifactType: container

# - task: PublishBuildArtifacts@1
#  displayName: Publish Deployment Scripts
#  inputs:
#    pathToPublish: deploy
#    artifactName: deploy
#    artifactType: container